export const USER_REQUEST = 'USER_REQUEST';
export const USER_AUTH_SUCCESS = 'USER_AUTH_SUCCESS';
export const USER_FAIL = 'USER_FAIL';

export const USER_CHATS_REQUEST = 'USER_CHATS_REQUEST';
export const USER_CHATS_FAIL = 'USER_CHATS_FAIL';
export const USER_CHATS_GET_SUCCESS = 'USER_CHATS_GET_SUCCESS';
export const USER_CHATS_SUBSCRIBE_SUCCESS = 'USER_CHATS_SUBSCRIBE_SUCCESS';
export const USER_CHATS_NO_MORE = 'USER_CHATS_NO_MORE';


export const CHATS_REQUEST = 'CHATS_REQUEST';
export const CHATS_CREATE_SUCCESS = 'CHATS_CREATE_SUCCESS';
export const CHATS_GET_SUCCESS = 'CHATS_GET_SUCCESS';
export const CHATS_NEW_MESSAGE = 'CHATS_NEW_MESSAGE';
export const CHATS_MEMBERS_GET_SUCCESS = 'CHATS_MEMBERS_GET_SUCCESS';
export const CHATS_MESSAGES_GET_SUCCESS = 'CHATS_MESSAGES_GET_SUCCESS';
export const CHATS_MESSAGE_POST_SUCCESS = 'CHATS_MESSAGE_POST_SUCCESS';
export const CHATS_FAIL = 'CHATS_FAIL';
export const CHATS_USER_JOIN = 'CHATS_USER_JOIN';
export const CHATS_USER_LEAVE = 'CHAT_USER_LEAVE';
export const CHATS_NO_MORE = 'CHATS_NO_MORE';

export const UI_CHANGE_CHATS_SEGMENT = 'UI_CHANGE_CHATS_SEGMENT';